<a href="https://colab.research.google.com/github/victorjrvieiras/Dados_TCC/blob/main/Dados_TCC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [21]:
dados = pd.read_csv('/content/scopus (3).csv')
dados_filtrados = dados[dados['Cited by'] > 20]
dados_filtrados

,Authors,Author full names,Author(s) ID,Title,Year,Source title,Volume,Issue,Art. No.,Page start,Page end,Page count,Cited by,DOI,Link,Document Type,Publication Stage,Open Access,Source,EID
65,Karatayev A.Y.; Burlakova L.E.,"Karatayev, Alexander Y. (6603502425); Burlakov...",6603502425; 6602258596,What we know and don’t know about the invasive...,2025,Hydrobiologia,852,5,e5211,1029,1102,73.0,47,10.1007/s10750-022-04950-5,https://www.scopus.com/inward/record.uri?eid=2...,Review,Final,All Open Access; Bronze Open Access; Green Ope...,Scopus,2-s2.0-85140083533
163,Sandri S.; Hussein H.; Alshyab N.; Sagatowski J.,"Sandri, Serena (28167824400); Hussein, Hussam ...",28167824400; 57189929116; 57202254523; 5849920...,The European Green Deal: Challenges and opport...,2025,Mediterranean Politics,30,1,NaN,196,207,11.0,21,10.1080/13629395.2023.2237295,https://www.scopus.com/inward/record.uri?eid=2...,Article,Final,All Open Access; Hybrid Gold Open Access,Scopus,2-s2.0-85165443185
184,Banaee M.; Multisanti C.R.; Impellitteri F.; P...,"Banaee, Mahdi (24075432400); Multisanti, Crist...",24075432400; 57778515300; 58071627600; 7004337...,Environmental toxicology of microplastic parti...,2025,Comparative Biochemistry and Physiology Part -...,287,NaN,110042,NaN,NaN,NaN,23,10.1016/j.cbpc.2024.110042,https://www.scopus.com/inward/record.uri?eid=2...,Review,Final,All Open Access; Hybrid Gold Open Access,Scopus,2-s2.0-85204738373
207,Peiman S.; Maleki B.; Ghani M.,"Peiman, Sahar (56149451200); Maleki, Behrooz (...",56149451200; 6506335669; 56030308100,Fe3O4@gC3N4@Thiamine: a novel heterogeneous ca...,2024,Scientific Reports,14,1,21488,NaN,NaN,NaN,24,10.1038/s41598-024-72212-6,https://www.scopus.com/inward/record.uri?eid=2...,Article,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-85203958646
453,Leal Filho W.; Ribeiro P.C.C.; Setti A.F.F.; A...,"Leal Filho, Walter (57189717187); Ribeiro, Pri...",57189717187; 36543040000; 36873378100; 3649914...,Toward food waste reduction at universities,2024,"Environment, Development and Sustainability",26,7,NaN,16585,16606,21.0,23,10.1007/s10668-023-03300-2,https://www.scopus.com/inward/record.uri?eid=2...,Article,Final,All Open Access; Bronze Open Access; Green Ope...,Scopus,2-s2.0-85158171171
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4613,Tanaka N.; Kubo K.; Yoshimura H.; Shiraki K.; ...,"Tanaka, Noriko (7404271762); Kubo, Katsuharu (...",7404271762; 57647489000; 7402345459; 720160861...,A pilot study on protein metabolism in the pap...,1980,Journal of Nutritional Science and Vitaminology,26,3,NaN,247,259,12.0,49,10.3177/jnsv.26.247,https://www.scopus.com/inward/record.uri?eid=2...,Article,Final,All Open Access; Gold Open Access,Scopus,2-s2.0-0019246480
4616,Norton B.W.; MacKintosh J.B.; Armstrong D.G.,"Norton, B.W. (7102113896); MacKintosh, J.B. (7...",7102113896; 7005980532; 9037384000,Urea synthesis and degradation in sheep given ...,1982,British Journal of Nutrition,48,2,NaN,249,264,15.0,33,10.1079/BJN19820111,https://www.scopus.com/inward/record.uri?eid=2...,Article,Final,All Open Access; Bronze Open Access,Scopus,2-s2.0-0020183824
4617,Allen R.D.,"Allen, Richard D. (35588831600)",35588831600,Food vacuole membrane growth with microtubule-...,1974,Journal of Cell Biology,63,3,NaN,904,922,18.0,106,10.1083/jcb.63.3.904,https://www.scopus.com/inward/record.uri?eid=2...,Article,Final,All Open Access; Green Open Access,Scopus,2-s2.0-0016289173
4619,Okajima F.; Ui M.,"Okajima, F. (7006200920); Ui, M. (7103128155)",7006200920; 7103128155,Metabolism of glucose in hyper- and hypo-thyro...,1979,Biochemical Journal,182,2,NaN,577,584,7.0,27,10.1042/bj1820577,https://www.scopus.com/inward/record.uri?eid=2...,Article,Final,All Open Access; Green Open Access,Scopus,2-s2.0-0018676160
4620,Davies N.T.; Nightingale R.,"Davies, N.T. (7202610623); Nightingale, R. (70...",7202610623; 7006433137,The effects of phytate on intestinal absorptio...,1975,British Journal of Nutrition,34,2,NaN,243,258,15.0,249,10.1017/s0007114575000293,https://www.scopus.com/inward/record.uri?eid=2...,Article,Final,All Open Access; Bronze Open Access,Scopus,2-s2.0-0016824107

In [37]:
citacoes_ordenada = dados_filtrados.groupby('Title')['Cited by'].mean()
citacoes_ordenada = citacoes_ordenada.sort_values(ascending=False)

In [38]:
df_resultado = citacoes_ordenada.reset_index()

In [39]:
df_resultado.to_csv('/content/citacoes_ordenada.csv', index = False)

In [41]:
df_resultado.to_excel('/content/citacoes_ordenada.xlsx', index=False)

In [42]:
df_resultado

                                                  Title  Cited by
0     An overview of chemical additives present in p...    2641.0
1     Environmental, economic, and energetic costs a...    2380.0
2     Safeguarding human health in the Anthropocene ...    1838.0
3           Policy: Classify plastic waste as hazardous    1346.0
4     Eutrophication of Chesapeake Bay: Historical t...    1191.0
...                                                 ...       ...
1534  Co-creating Agroecological Symbioses (AES) for...      21.0
1535  Improving Life Cycle Economic and Environmenta...      21.0
1536  Cutting Techniques in the Fish Industry: A Cri...      21.0
1537  Rainfall recycling needs to be considered in d...      21.0
1538  Continuous production of organic acids from pa...      21.0

[1539 rows x 2 columns]